// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhgTQEVFNecl7z98jQQ_kSvWgAXexO8PQ',
    appId: '1:991271409178:web:453e82c53063c0876a63a3',
    messagingSenderId: '991271409178',
    projectId: 'team-pe',
    authDomain: 'team-pe.firebaseapp.com',
    storageBucket: 'team-pe.appspot.com',
    measurementId: 'G-CPM0FCLZK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVCL5wGz1xWka9aKTnBKhzS5TRrajvLVs',
    appId: '1:991271409178:android:8eebf3449c65a81a6a63a3',
    messagingSenderId: '991271409178',
    projectId: 'team-pe',
    storageBucket: 'team-pe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPvNAypaYzalELJbpf600LDJ-Z6atn4I',
    appId: '1:991271409178:ios:72443c177257da006a63a3',
    messagingSenderId: '991271409178',
    projectId: 'team-pe',
    storageBucket: 'team-pe.appspot.com',
    iosBundleId: 'com.example.airsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPvNAypaYzalELJbpf600LDJ-Z6atn4I',
    appId: '1:991271409178:ios:24b4a92eaf2a80f16a63a3',
    messagingSenderId: '991271409178',
    projectId: 'team-pe',
    storageBucket: 'team-pe.appspot.com',
    iosBundleId: 'com.example.airsense.RunnerTests',
  );
}
